

export const CANCELLED = 'Cancelled';
export const BOOKED = 'Booked';


export const ADD_DATE = 'ADD_DATE';
export const ADD_CUSTOMER_LIST = 'ADD_CUSTOMER_LIST';

export const ADD_APPOINTMENT_LIST = 'ADD_APPOINTMENT_LIST';
export const DELETE_APPOINTMENT_LIST = 'DELETE_APPOINTMENT_LIST';
export const UPDATE_APPOINTMENT_LIST = 'UPDATE_APPOINTMENT_LIST';


export const ADD_STAFF_LIST = 'ADD_STAFF_LIST';
export const DELETE_STAFF_LIST = 'DELETE_STAFF_LIST';
export const UPDATE_STAFF_LIST = 'UPDATE_STAFF_LIST';
