export const getAppointmentData= {
    "appointments":[
        {
            "id":456827101,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":14,
            "treatment_Name":"Gentlemen's Facial",
            "billable_Item_Id":1800929,
            "employee_Id":51592,
            "employee_Name":"Millicent Hilliam",
            "status":"Booked",
            "booked_Date":"2020-02-06T14:48:00",
            "start_Date":"2020-08-15T09:15:00",
            "end_Date":"2020-08-15T10:00:00",
            "cancellation_Type":"",
            "customer_Id":138500068,
            "customer_Name":"Bartlett Claessens",
            "customer_Age":39,
            "customer_Gender":"Male",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":91.836334
        },
        {
            "id":458646744,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":10,
            "treatment_Name":"Brazilian Waxing",
            "billable_Item_Id":1800929,
            "employee_Id":523090,
            "employee_Name":"Keene Millea",
            "status":"Booked",
            "booked_Date":"2020-02-14T14:23:00",
            "start_Date":"2020-08-15T10:15:00",
            "end_Date":"2020-08-15T11:00:00",
            "cancellation_Type":"",
            "customer_Id":138496349,
            "customer_Name":"Janela Asbery",
            "customer_Age":34,
            "customer_Gender":"Female",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":89.62109
        },
        {
            "id":459396263,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":19,
            "treatment_Name":"Oyster Shell Powder Scrub",
            "billable_Item_Id":1800929,
            "employee_Id":523090,
            "employee_Name":"Keene Millea",
            "status":"Booked",
            "booked_Date":"2020-02-18T14:47:00",
            "start_Date":"2020-08-15T10:15:00",
            "end_Date":"2020-08-15T11:00:00",
            "cancellation_Type":"",
            "customer_Id":139253645,
            "customer_Name":"Booth Westney",
            "customer_Age":44,
            "customer_Gender":"Male",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":91.03562
        },
        {
            "id":467519839,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":14,
            "treatment_Name":"Gentlemen's Facial",
            "billable_Item_Id":1800929,
            "employee_Id":523090,
            "employee_Name":"Keene Millea",
            "status":"Booked",
            "booked_Date":"2020-05-24T12:48:00",
            "start_Date":"2020-08-15T10:15:00",
            "end_Date":"2020-08-15T11:00:00",
            "cancellation_Type":"",
            "customer_Id":138503982,
            "customer_Name":"Benjamin Kennerley",
            "customer_Age":43,
            "customer_Gender":"Male",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":86.979034
        },
        {
            "id":472616375,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":8,
            "treatment_Name":"Half Legs  Waxing",
            "billable_Item_Id":1800929,
            "employee_Id":274753,
            "employee_Name":"Micki McTurlough",
            "status":"Booked",
            "booked_Date":"2020-07-02T14:03:00",
            "start_Date":"2020-08-15T13:45:00",
            "end_Date":"2020-08-15T14:15:00",
            "cancellation_Type":"",
            "customer_Id":155221248,
            "customer_Name":"Adlai Shuker",
            "customer_Age":51,
            "customer_Gender":"Male",
            "treatment_Duration":30,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":30.898512
        },
        {
            "id":465128453,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":18,
            "treatment_Name":"Neem Body Polish",
            "billable_Item_Id":1800929,
            "employee_Id":957791,
            "employee_Name":"Titus Lakey",
            "status":"Booked",
            "booked_Date":"2020-03-19T15:14:00",
            "start_Date":"2020-08-15T14:45:00",
            "end_Date":"2020-08-15T15:30:00",
            "cancellation_Type":"",
            "customer_Id":138492605,
            "customer_Name":"Edlin Rosnau",
            "customer_Age":52,
            "customer_Gender":"Male",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":99.53721
        },
        {
            "id":465036876,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":20,
            "treatment_Name":"Antioxidant Body Wrap",
            "billable_Item_Id":1800929,
            "employee_Id":887406,
            "employee_Name":"Lamond Cayette",
            "status":"Booked",
            "booked_Date":"2020-03-18T13:10:00",
            "start_Date":"2020-08-15T16:00:00",
            "end_Date":"2020-08-15T17:00:00",
            "cancellation_Type":"",
            "customer_Id":138495206,
            "customer_Name":"Selle Bloore",
            "customer_Age":31,
            "customer_Gender":"Female",
            "treatment_Duration":60,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":99.253555
        },
        {
            "id":465166581,
            "location_Id":3510,
            "business_Type":"Spa",
            "business_Type_Id":30.0,
            "state":"QC",
            "country":"Canada",
            "treatment_Id":9,
            "treatment_Name":"Full Legs Waxing",
            "billable_Item_Id":1800929,
            "employee_Id":976588,
            "employee_Name":"Cy Bolsteridge",
            "status":"Booked",
            "booked_Date":"2020-03-20T08:41:00",
            "start_Date":"2020-08-15T19:15:00",
            "end_Date":"2020-08-15T20:00:00",
            "cancellation_Type":"",
            "customer_Id":138911858,
            "customer_Name":"Maddy Simenet",
            "customer_Age":28,
            "customer_Gender":"Male",
            "treatment_Duration":45,
            "fee_Amount":0,
            "cancellation_Fee_Status":"",
            "cancellation_Policy":"YES",
            "probability":99.36071
        }
    ],
    "employees":[
        {
            "employeeId":51592,
            "employeeName":"Millicent Hilliam"
        },
        {
            "employeeId":523090,
            "employeeName":"Keene Millea"
        },
        {
            "employeeId":274753,
            "employeeName":"Micki McTurlough"
        },
        {
            "employeeId":957791,
            "employeeName":"Titus Lakey"
        },
        {
            "employeeId":887406,
            "employeeName":"Lamond Cayette"
        },
        {
            "employeeId":976588,
            "employeeName":"Cy Bolsteridge"
        }
    ]
};
