export const booking = [
    {
        "appointmentID": 349572160,
        "startDateTime": "2018-09-28T09:30:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T11:13:00",
        "treatmentDuration": 15,
        "customerName": "SarahSimon Ginsberg",
        "employeeName": "BAINDUKOROMA",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349572161,
        "startDateTime": "2018-09-28T09:30:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T11:13:00",
        "treatmentDuration": 15,
        "customerName": "222SarahSimon Ginsberg",
        "employeeName": "BAINDUKOROMA",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349598050,
        "startDateTime": "2018-09-29T15:15:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T12:21:00",
        "treatmentDuration": 35,
        "customerName": "CarissaNg",
        "employeeName": "JOANIEGUDERIAN",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349607580,
        "startDateTime": "2018-09-25T13:30:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T12:44:00",
        "treatmentDuration": 35,
        "customerName": "MarshaSokolovskaya",
        "employeeName": "STEPHANIESANTIAGO",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349609400,
        "startDateTime": "2018-09-25T19:30:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T12:49:00",
        "treatmentDuration": 35,
        "customerName": "KaRen Castellano",
        "employeeName": "JOANIEGUDERIAN",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349634460,
        "startDateTime": "2018-09-27T09:00:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T13:50:00",
        "treatmentDuration": 35,
        "customerName": "BridgetO'Connor",
        "employeeName": "ASHLEYDAVILA",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349649980,
        "startDateTime": "2018-10-01T14:00:00",
        "statusID": 6,
        "appointmentStatus": "Cancelled",
        "dateBooked": "2018-09-25T14:27:00",
        "treatmentDuration": 35,
        "customerName": "DeniseDiianni",
        "employeeName": "BRIACAPERS",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349656740,
        "startDateTime": "2018-09-28T09:00:00",
        "statusID": 6,
        "appointmentStatus": "Cancelled",
        "dateBooked": "2018-09-25T14:45:00",
        "treatmentDuration": 15,
        "customerName": "PhilippaHose",
        "employeeName": "DAWNCRAWFORD",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349683700,
        "startDateTime": "2018-09-26T19:00:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T16:00:00",
        "treatmentDuration": 35,
        "customerName": "KariSchak",
        "employeeName": "MICHAELPLEAKE",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349693600,
        "startDateTime": "2018-09-26T09:00:00",
        "statusID": 5,
        "appointmentStatus": "Paid/Complete",
        "dateBooked": "2018-09-25T16:28:00",
        "treatmentDuration": 35,
        "customerName": "geraldinewarner",
        "employeeName": "GIAMNARODRIGUEZ",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    },
    {
        "appointmentID": 349694460,
        "startDateTime": "2018-10-06T13:00:00",
        "statusID": 6,
        "appointmentStatus": "Cancelled",
        "dateBooked": "2018-09-25T16:31:00",
        "treatmentDuration": 35,
        "customerName": "MonicaCreelman",
        "employeeName": "DARRELLMARTIN",
        "employee2Name": "",
        "serviceName": "Blow out",
        "locationName": "Drybar 71st St. in Upper West Side",
        "locationID": 29178,
        "city": "New York",
        "country": "United States",
        "state": "NY",
        "zip": 10023,
        "feeStatus": "NULL",
        "feeAmount": "NULL"
    }
]


